#version: "3.8"
#
#services:
#  kafka:
#    image: confluentinc/cp-kafka:7.6.1
#    container_name: kafka
#    ports:
#      - "9092:9092"
#      - "29092:29092"
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
#
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#
#    volumes:
#      - kafka-data:/var/lib/kafka/data
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "8080:8080"
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
#    depends_on:
#      - kafka
#
#  spark-master:
#    image: bitnami/spark:3.5.1
#    container_name: spark-master
#    ports:
#      - "7077:7077"
#      - "4040:4040"
#    environment:
#      - SPARK_MODE=master
#    volumes:
#      - ./spark-apps:/opt/spark-apps
#
#  spark-worker:
#    image: bitnami/spark:3.5.1
#    container_name: spark-worker
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark-master:7077
#    depends_on:
#      - spark-master
#
#volumes:
#  kafka-data:
